export const SWAGGER_MESSAGES = {
  LOGIN: "Registered User Login Here",
  LOGUT:"Loged in user logout here" ,
  DELETE_FAVORITE_PRODUCT: "Delete Favorite Product By Product Id",
  DELETE_ALL_FAV_PRO: "Delete All Favorite Product of Current User",
  ADD_FAV_ITEM: "Add Favorite Items to Your Cart",
  GET_ALL_FAV_PRO: "Get All Your Favorite Products",
  ADD_PRODUCT:"Add new product Here",
  UPDATE_OFFERS: "Update Existing Offers",
  CREATE_OFFER: "Create An Offer for Existing Users",
  PRODUCT_UPDATE: "Update Existing Product Product Here",
  GET_ALL_PROD: "Get All Products by Searcing, Sorting and Filtering",
  UPDATE_PROFILE: "Update Your Profile Picture Here",
  UPLOAD_PROFILE: "Upload Your Profile Picture Here",
  SUBMIT_REVIEW: "Submit Review for product",
  UPDATE_REVIEW: "Update Review for product",
  DELETE_REVIEW: "Delete Review for product",
  GET_USERS: "Get Users By Providing Id",
  GET_ALL_USERS: "Get All Users by Searcing, Sorting and Filtering",
  REGISTER: "Don't have Account Register Here",
  DELETE_ITEM_FROM_CART: "Delete Item from Your cart",
  GET_ALL_PROD_FROM_CART: "Get All Items from your Cart",
  UPDATE_PROD_FROM_CART: "Update product to Your Cart",
  ADD_PROD_TO_CART: "Add product to Your Cart",
  DELETE: "Delete a user from database",
};
